### ISSUE TITLE
SLAM doesn't work in Gazebo

### ISSUE THREAD

**Issue by marian42** [Autonomous-Racing-PG/ar-tu-do#338]
Since #337, SLAM works better on the real car, but no longer works in Gazebo, since the IMU isn't used.

I'm not sure what the best solution is, possibilities are:
- add two scripts, one that uses the IMU, one that doesn't
- detect if an IMU is available???
- revert #337

**Comment by Nils-Jung** [comment]
To be honest I think it should stay as it is although I don't really care either way. The way it is currently set up is the current best configuration for our car. Since our end goal is autonomous driving on the physical car I think the parameters necessary for that should be the default. Detecting an IMU and switching the parameters automatically would probably be possible (listening on topic "/imu"?) but that just introduces another point of possible failure. Similarly, having two different parameter files means it is necessary to somehow keep both of them in sync which is not ideal.
I know it is not a great solution but since the SLAM algorithm *technically* works in Gazebo and changing the parameters is more or less trivial (in `/ros_ws/src/navigation_stack/car_cartographer/config/cartographer_config_<ros_version>.lua` set `TRAJECTORY_BUILDER_2D.use_imu_data` to `true`) I think it should stay as it is.
